/**
 * Generator module — produces mock server code, TypeScript types, and client SDK
 * from the intermediate representation (IR).
 */

const { fakeObject, fakeArray, fakeValue, uuid, randInt } = require('./faker');

// ─── Mock Server Generator ───────────────────────────────────────────────────

/**
 * Generate a standalone Express mock server as a string of JS code.
 */
function generateMockServer(ir, config = {}) {
  const {
    delay = 0,
    errorRate = 0,
    pagination = true,
    port = 4000,
    corsOrigin = '*',
  } = config;

  const routes = ir.endpoints.map(ep => generateRoute(ep, ir, { delay, errorRate, pagination }));

  return `#!/usr/bin/env node
/**
 * ${ir.info.title} v${ir.info.version}
 * ${ir.info.description || 'Auto-generated mock server'}
 *
 * Generated by api-mock-generator
 */
const express = require('express');
const cors = require('cors');

const app = express();
app.use(cors({ origin: '${corsOrigin}' }));
app.use(express.json());

// ── Request Logger ──────────────────────────────────────────────────────────
const requestLog = [];
app.use((req, res, next) => {
  const entry = {
    id: requestLog.length + 1,
    timestamp: new Date().toISOString(),
    method: req.method,
    path: req.path,
    query: req.query,
    headers: {
      'content-type': req.headers['content-type'],
      'authorization': req.headers['authorization'] ? '[PRESENT]' : undefined,
      'user-agent': req.headers['user-agent'],
    },
    body: req.body && Object.keys(req.body).length ? req.body : undefined,
  };
  requestLog.push(entry);
  if (requestLog.length > 1000) requestLog.shift();
  console.log(\`[\${entry.timestamp}] \${req.method} \${req.path}\`);
  next();
});

// ── Health & Log Endpoints ──────────────────────────────────────────────────
app.get('/health', (req, res) => res.json({ status: 'ok', uptime: process.uptime() }));
app.get('/_logs', (req, res) => {
  const limit = parseInt(req.query.limit) || 50;
  res.json(requestLog.slice(-limit));
});
app.delete('/_logs', (req, res) => {
  requestLog.length = 0;
  res.json({ success: true, message: 'Logs cleared' });
});

// ── Config Endpoint ─────────────────────────────────────────────────────────
let mockConfig = { delay: ${delay}, errorRate: ${errorRate}, pagination: ${pagination} };
app.get('/_config', (req, res) => res.json(mockConfig));
app.put('/_config', (req, res) => {
  mockConfig = { ...mockConfig, ...req.body };
  res.json(mockConfig);
});

// ── Helpers ─────────────────────────────────────────────────────────────────
function maybeDelay(req, res, next) {
  if (mockConfig.delay > 0) {
    setTimeout(next, mockConfig.delay);
  } else {
    next();
  }
}

function maybeError(req, res, next) {
  if (mockConfig.errorRate > 0 && Math.random() < mockConfig.errorRate) {
    const codes = [400, 401, 403, 404, 500, 502, 503];
    const code = codes[Math.floor(Math.random() * codes.length)];
    return res.status(code).json({
      error: true,
      statusCode: code,
      message: \`Simulated \${code} error (errorRate: \${mockConfig.errorRate})\`,
    });
  }
  next();
}

app.use(maybeDelay);
app.use(maybeError);

// ── Mock Data Store (in-memory) ─────────────────────────────────────────────
const store = {};
function getStore(key, defaultData) {
  if (!store[key]) store[key] = typeof defaultData === 'function' ? defaultData() : [...(defaultData || [])];
  return store[key];
}

${routes.join('\n\n')}

// ── 404 Handler ─────────────────────────────────────────────────────────────
app.use((req, res) => {
  res.status(404).json({
    error: true,
    statusCode: 404,
    message: \`Route not found: \${req.method} \${req.path}\`,
    availableEndpoints: [
${ir.endpoints.map(ep => `      '${ep.method} ${ep.path}'`).join(',\n')},
      'GET /health',
      'GET /_logs',
      'GET /_config',
      'PUT /_config',
    ],
  });
});

// ── Start ───────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || ${port};
app.listen(PORT, () => {
  console.log(\`\\n  ${ir.info.title} v${ir.info.version}\`);
  console.log(\`  Mock server running at http://localhost:\${PORT}\`);
  console.log(\`  ${ir.endpoints.length} endpoints ready\\n\`);
  console.log('  Endpoints:');
${ir.endpoints.map(ep => `  console.log('    ${ep.method.padEnd(7)} ${ep.path}');`).join('\n')}
  console.log('\\n  Utility:');
  console.log('    GET     /health');
  console.log('    GET     /_logs');
  console.log('    GET     /_config');
  console.log('    PUT     /_config');
  console.log('');
});
`;
}

function generateRoute(ep, ir, config) {
  const method = ep.method.toLowerCase();
  const responseSchema = ep.responses?.['200']?.schema || ep.responses?.['201']?.schema;
  const statusCode = ep.responses?.['201'] ? 201 : 200;

  // Determine the resource name from path for store key
  const pathParts = ep.path.split('/').filter(Boolean);
  const resourceKey = pathParts.find(p => !p.startsWith(':')) || 'items';

  let handler;

  if (method === 'get' && !ep.path.includes(':id')) {
    // LIST endpoint with optional pagination
    handler = generateListHandler(resourceKey, responseSchema, config, ir);
  } else if (method === 'get' && ep.path.includes(':id')) {
    // GET single
    handler = generateGetHandler(resourceKey, responseSchema, ir);
  } else if (method === 'post') {
    handler = generatePostHandler(resourceKey, responseSchema, statusCode, ir);
  } else if (method === 'put' || method === 'patch') {
    handler = generatePutHandler(resourceKey, responseSchema, ir);
  } else if (method === 'delete') {
    handler = generateDeleteHandler(resourceKey);
  } else {
    handler = generateGenericHandler(responseSchema, statusCode, ir);
  }

  return `// ${ep.summary || ep.operationId}
app.${method}('${ep.path}', (req, res) => {
${handler}
});`;
}

function schemaToInlineData(schema, ir) {
  if (!schema) return 'null';
  if (schema.type === 'array' && schema.items) {
    const itemSchema = schema.items.$ref
      ? resolveSchemaRef(schema.items.$ref, ir)
      : schema.items;
    if (itemSchema?.properties) {
      const data = fakeArray(itemSchema.properties, itemSchema.required, 10);
      return JSON.stringify(data, null, 2);
    }
    return '[]';
  }
  if (schema.properties) {
    const data = fakeObject(schema.properties, schema.required);
    return JSON.stringify(data, null, 2);
  }
  return JSON.stringify(fakeValue(null, schema));
}

function resolveSchemaRef(ref, ir) {
  if (!ref) return null;
  const name = ref.split('/').pop();
  return ir.schemas?.[name] || null;
}

function generateListHandler(resourceKey, schema, config, ir) {
  const seedData = schemaToInlineData(schema, ir);
  return `  const items = getStore('${resourceKey}', ${seedData});
  if (mockConfig.pagination) {
    const page = parseInt(req.query.page) || 1;
    const limit = Math.min(parseInt(req.query.limit) || 10, 100);
    const start = (page - 1) * limit;
    const paged = items.slice(start, start + limit);
    return res.json({
      data: paged,
      pagination: {
        page,
        limit,
        total: items.length,
        totalPages: Math.ceil(items.length / limit),
        hasNext: start + limit < items.length,
        hasPrev: page > 1,
      },
    });
  }
  res.json(items);`;
}

function generateGetHandler(resourceKey, schema, ir) {
  const fallback = schema?.properties
    ? JSON.stringify(fakeObject(schema.properties, schema.required), null, 2)
    : '{}';
  return `  const items = getStore('${resourceKey}', []);
  const item = items.find(i => i.id === req.params.id);
  if (item) return res.json(item);
  // Return generated fallback
  res.json({ ...${fallback}, id: req.params.id });`;
}

function generatePostHandler(resourceKey, schema, statusCode, ir) {
  const defaults = schema?.properties
    ? JSON.stringify(fakeObject(schema.properties, schema.required), null, 2)
    : '{}';
  return `  const items = getStore('${resourceKey}', []);
  const newItem = {
    ...${defaults},
    ...req.body,
    id: req.body.id || '${uuid()}' + '-' + Date.now().toString(36),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  items.push(newItem);
  res.status(${statusCode}).json(newItem);`;
}

function generatePutHandler(resourceKey, schema, ir) {
  const defaults = schema?.properties
    ? JSON.stringify(fakeObject(schema.properties, schema.required), null, 2)
    : '{}';
  return `  const items = getStore('${resourceKey}', []);
  const idx = items.findIndex(i => i.id === req.params.id);
  if (idx !== -1) {
    items[idx] = { ...items[idx], ...req.body, updatedAt: new Date().toISOString() };
    return res.json(items[idx]);
  }
  res.json({ ...${defaults}, ...req.body, id: req.params.id, updatedAt: new Date().toISOString() });`;
}

function generateDeleteHandler(resourceKey) {
  return `  const items = getStore('${resourceKey}', []);
  const idx = items.findIndex(i => i.id === req.params.id);
  if (idx !== -1) items.splice(idx, 1);
  res.json({ success: true, message: 'Deleted', id: req.params.id });`;
}

function generateGenericHandler(schema, statusCode, ir) {
  const data = schemaToInlineData(schema, ir);
  return `  res.status(${statusCode}).json(${data});`;
}

// ─── TypeScript Type Generator ───────────────────────────────────────────────

function generateTypes(ir) {
  const lines = [
    `/**`,
    ` * ${ir.info.title} v${ir.info.version}`,
    ` * Auto-generated TypeScript types`,
    ` */`,
    '',
  ];

  // Generate interfaces from schemas
  for (const [name, schema] of Object.entries(ir.schemas || {})) {
    lines.push(...schemaToInterface(name, schema));
    lines.push('');
  }

  // Generate interfaces from response schemas
  const generated = new Set(Object.keys(ir.schemas || {}));
  for (const ep of ir.endpoints) {
    for (const [code, resp] of Object.entries(ep.responses || {})) {
      if (resp.schema && resp.schema.properties && !findExistingSchemaName(resp.schema, ir)) {
        const name = toPascalCase(ep.operationId) + 'Response';
        if (!generated.has(name)) {
          generated.add(name);
          lines.push(...schemaToInterface(name, resp.schema));
          lines.push('');
        }
      }
    }
    if (ep.requestBody?.properties) {
      const name = toPascalCase(ep.operationId) + 'Request';
      if (!generated.has(name)) {
        generated.add(name);
        lines.push(...schemaToInterface(name, ep.requestBody));
        lines.push('');
      }
    }
  }

  // Pagination wrapper
  lines.push('export interface PaginatedResponse<T> {');
  lines.push('  data: T[];');
  lines.push('  pagination: {');
  lines.push('    page: number;');
  lines.push('    limit: number;');
  lines.push('    total: number;');
  lines.push('    totalPages: number;');
  lines.push('    hasNext: boolean;');
  lines.push('    hasPrev: boolean;');
  lines.push('  };');
  lines.push('}');
  lines.push('');

  // API Error
  lines.push('export interface ApiError {');
  lines.push('  error: true;');
  lines.push('  statusCode: number;');
  lines.push('  message: string;');
  lines.push('}');

  return lines.join('\n');
}

function schemaToInterface(name, schema, indent = '') {
  const lines = [];
  lines.push(`${indent}export interface ${name} {`);
  if (schema.properties) {
    for (const [key, prop] of Object.entries(schema.properties)) {
      const optional = !(schema.required || []).includes(key) ? '?' : '';
      const tsType = schemaToTsType(prop);
      lines.push(`${indent}  ${key}${optional}: ${tsType};`);
    }
  }
  lines.push(`${indent}}`);
  return lines;
}

function schemaToTsType(schema) {
  if (!schema) return 'unknown';
  if (schema.enum) return schema.enum.map(v => `'${v}'`).join(' | ');

  switch (schema.type) {
    case 'string':
      return 'string';
    case 'integer':
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (schema.items) {
        if (schema.items.type === 'object' && schema.items.properties) {
          const props = Object.entries(schema.items.properties)
            .map(([k, v]) => `${k}: ${schemaToTsType(v)}`)
            .join('; ');
          return `Array<{ ${props} }>`;
        }
        return `${schemaToTsType(schema.items)}[]`;
      }
      return 'unknown[]';
    case 'object':
      if (schema.properties) {
        const props = Object.entries(schema.properties)
          .map(([k, v]) => `${k}: ${schemaToTsType(v)}`)
          .join('; ');
        return `{ ${props} }`;
      }
      return 'Record<string, unknown>';
    default:
      return 'unknown';
  }
}

function findExistingSchemaName(schema, ir) {
  // Simple heuristic — check if properties match
  for (const [name, s] of Object.entries(ir.schemas || {})) {
    if (s.properties && schema.properties) {
      const keys1 = Object.keys(s.properties).sort().join(',');
      const keys2 = Object.keys(schema.properties).sort().join(',');
      if (keys1 === keys2) return name;
    }
  }
  return null;
}

function toPascalCase(str) {
  return str.replace(/[_-](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, c => c.toUpperCase());
}

// ─── Client SDK Generator ────────────────────────────────────────────────────

function generateClient(ir, config = {}) {
  const { baseUrl = 'http://localhost:4000', typescript = true } = config;

  const lines = [
    `/**`,
    ` * ${ir.info.title} v${ir.info.version}`,
    ` * Auto-generated API Client`,
    ` */`,
    '',
  ];

  if (typescript) {
    lines.push(`type RequestOptions = {`);
    lines.push(`  headers?: Record<string, string>;`);
    lines.push(`  signal?: AbortSignal;`);
    lines.push(`};`);
    lines.push('');
  }

  lines.push(`class ApiClient {`);
  lines.push(`  private baseUrl: string;`);
  lines.push(`  private defaultHeaders: Record<string, string>;`);
  lines.push('');
  lines.push(`  constructor(baseUrl: string = '${baseUrl}', headers: Record<string, string> = {}) {`);
  lines.push(`    this.baseUrl = baseUrl.replace(/\\/$/, '');`);
  lines.push(`    this.defaultHeaders = {`);
  lines.push(`      'Content-Type': 'application/json',`);
  lines.push(`      ...headers,`);
  lines.push(`    };`);
  lines.push(`  }`);
  lines.push('');
  lines.push(`  setToken(token: string) {`);
  lines.push(`    this.defaultHeaders['Authorization'] = \`Bearer \${token}\`;`);
  lines.push(`    return this;`);
  lines.push(`  }`);
  lines.push('');

  // Generic request method
  lines.push(`  private async request<T>(method: string, path: string, body?: unknown, options?: RequestOptions): Promise<T> {`);
  lines.push(`    const url = \`\${this.baseUrl}\${path}\`;`);
  lines.push(`    const res = await fetch(url, {`);
  lines.push(`      method,`);
  lines.push(`      headers: { ...this.defaultHeaders, ...options?.headers },`);
  lines.push(`      body: body ? JSON.stringify(body) : undefined,`);
  lines.push(`      signal: options?.signal,`);
  lines.push(`    });`);
  lines.push(`    if (!res.ok) {`);
  lines.push(`      const error = await res.json().catch(() => ({ message: res.statusText }));`);
  lines.push(`      throw Object.assign(new Error(error.message || \`HTTP \${res.status}\`), { status: res.status, data: error });`);
  lines.push(`    }`);
  lines.push(`    return res.json();`);
  lines.push(`  }`);
  lines.push('');

  // Generate methods for each endpoint
  for (const ep of ir.endpoints) {
    const methodName = toCamelCase(ep.operationId);
    const pathParams = (ep.parameters || []).filter(p => p.in === 'path');
    const queryParams = (ep.parameters || []).filter(p => p.in === 'query');
    const hasBody = ['POST', 'PUT', 'PATCH'].includes(ep.method) && ep.requestBody;

    const params = [];
    for (const p of pathParams) {
      params.push(`${p.name}: string`);
    }
    if (hasBody) {
      params.push(`body: Record<string, unknown>`);
    }
    if (queryParams.length) {
      params.push(`query?: Record<string, string | number>`);
    }
    params.push(`options?: RequestOptions`);

    // Build path with interpolation
    let pathExpr = ep.path.replace(/:(\w+)/g, (_, name) => `\${${name}}`);
    let queryExpr = '';
    if (queryParams.length) {
      queryExpr = ` + (query ? '?' + new URLSearchParams(Object.entries(query).map(([k,v]) => [k, String(v)])).toString() : '')`;
    }

    const comment = ep.summary ? `  /** ${ep.summary} */\n` : '';
    lines.push(`${comment}  async ${methodName}(${params.join(', ')}): Promise<unknown> {`);
    lines.push(`    return this.request('${ep.method}', \`${pathExpr}\`${queryExpr}, ${hasBody ? 'body' : 'undefined'}, options);`);
    lines.push(`  }`);
    lines.push('');
  }

  // Utility methods
  lines.push(`  /** Get request logs */`);
  lines.push(`  async getLogs(limit = 50): Promise<unknown> {`);
  lines.push(`    return this.request('GET', \`/_logs?limit=\${limit}\`);`);
  lines.push(`  }`);
  lines.push('');
  lines.push(`  /** Get/update mock config */`);
  lines.push(`  async getConfig(): Promise<unknown> {`);
  lines.push(`    return this.request('GET', '/_config');`);
  lines.push(`  }`);
  lines.push('');
  lines.push(`  async updateConfig(config: { delay?: number; errorRate?: number; pagination?: boolean }): Promise<unknown> {`);
  lines.push(`    return this.request('PUT', '/_config', config);`);
  lines.push(`  }`);

  lines.push(`}`);
  lines.push('');
  lines.push(`export default ApiClient;`);
  lines.push(`export { ApiClient };`);

  return lines.join('\n');
}

function toCamelCase(str) {
  return str.replace(/[_-](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, c => c.toLowerCase());
}

module.exports = { generateMockServer, generateTypes, generateClient };
